# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ff00343679e739d1c1505ad388f93069ab3230e944fa371ebd2344296f3f9aa29c172b0b24c8ca6af13404b67fae31bd154091b0258ed96de9840b26a6ddd9

test:
  secret_key_base: 8b40d2ad78dca0af6c81f1a8d769fd30fed64275a00a8ab6573b5c4797b1f39a88559ab0c56683ec73c26d890239b50f72107f984f5b4f5fd0b343e212f3f900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
